# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ai-playground',
                'doc_host': 'https://Foxicution.github.io',
                'git_url': 'https://github.com/Foxicution/ai-playground',
                'lib_path': 'ai_playground'},
  'syms': {'ai_playground.core': {'ai_playground.core.foo': ('core.html#foo', 'ai_playground/core.py')}}}
